server:
   port: 8197
   servlet:
      contextPath: /together
spring:
  servlet:
    mutipart:
      file-size-threshold: 1MB
      location: C:\Users\multicampus\Desktop\s02p13b109\ssafy-backend\together\UploadFile
      max-file-size: 100MB
      max-request-size: 100MB
      