server:
   port: 8197
   servlet:
      contextPath: /together
#   ssl:
#    key-store: /etc/letsencrypt/live/i02b109.p.ssafy.io/keystore.p12
#    key-store-password: together
#    key-store-type: PKCS12
#    key-alias: etogether

spring:
  servlet:
    mutipart:
      file-size-threshold: 100MB
      max-file-size: 100MB
      max-request-size: 100MB
      

